[package]
name = "emojis"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuzzy-matcher = { version = "0.3.7", optional = true }
itertools = { version = "0.10.0", optional = true }

[features]
std = []
default = ["search"]
search = ["std", "fuzzy-matcher", "itertools"]

[workspace]
members = ["generate"]
